version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    platform: linux/amd64
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dayparty
      - MONGO_INITDB_ROOT_PASSWORD=partyday
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
